#!/bin/bash

sudo -H -u edxapp bash -c "
  source /edx/app/edxapp/edxapp_env
  cd /edx/app/edxapp/edx-platform/
  if [ ! $1 ]; then
    paver update_assets lms --settings=aws
  else
    paver update_assets lms --settings=aws --themes=$1
  fi
"

